### ISSUE TITLE
Handling of on/off/true/false/yes/no in "allowed" values

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vss-tools#143]
The handling of on/off/true/false in allowed values for string signals differs from other keywords. I assume this is related to that Yaml in some way consider them as synonyms, and I believe this is not the wanted behavior for us. But what can we do:

- Changing tooling so that e.g. `on`  as a string allowed value remain as "on" in generated yaml/CSV
- Change our recommendation to always recommend use of quotes (then we must agree if single or double quotes are preferred) and inform that without quotes black magic may happen for some words. Of course we can list the words identified here but there might be more?

Any opinions? I am no Python/Yaml expert so it was not obvious for me where the conversion happens. Example below show handling of On/Off/True/False and a non-special word as reference. Similar behavior observed for yes/no. 

```
TmpOnOff:
  datatype: string
  type: sensor
  allowed: [on, "on", 'on', ON, "ON", 'ON', off, "off", 'off', OFF, "OFF", 'OFF']
  description: Different types of on/off
  
TmpTrueFalse:
  datatype: string
  type: sensor
  allowed: [false, "false", 'false', FALSE, "FALSE", 'FALSE', true, "true", 'true', TRUE, "TRUE", 'TRUE']
  description: Different types of true/false
  
   
TmpFeierabend:
  datatype: string
  type: sensor
  allowed: [feierabend,"feierabend",'feierabend',FEIERABEND, "FEIERABEND", 'FEIERABEND']
  description: Different types of Feierabend
```

Resulting Yaml, similar result received for CSV generator
```

Vehicle.TmpOnOff:
  type: sensor
  datatype: string
  allowed:
  - true
  - 'on'
  - 'on'
  - true
  - 'ON'
  - 'ON'
  - false
  - 'off'
  - 'off'
  - false
  - 'OFF'
  - 'OFF'
  description: Different types of on/off
  uuid: 1cfaa93b5b075b0ab294741827faa831

Vehicle.TmpTrueFalse:
  type: sensor
  datatype: string
  allowed:
  - false
  - 'false'
  - 'false'
  - false
  - 'FALSE'
  - 'FALSE'
  - true
  - 'true'
  - 'true'
  - true
  - 'TRUE'
  - 'TRUE'
  description: Different types of true/false
  uuid: 7fce7b577ff75682a0a3ea587aad65a9

Vehicle.TmpFeierabend:
  type: sensor
  datatype: string
  allowed:
  - feierabend
  - feierabend
  - feierabend
  - FEIERABEND
  - FEIERABEND
  - FEIERABEND
  description: Different types of Feierabend
  uuid: 8e8b71ea30c45926ad0348adad47ce27
```
