### ISSUE TITLE
AMM Idea: Overlays - introduce easy solution to add keys to multiple signals

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vss-tools#193]
Idea collected during AMM. In some cases you might want to add the same key/property to a large number of signals, e.g. add something like "included: true" to a large number of signals. A "shortcut" solution for doing this could be useful

**Comment by nwesem** [comment]
hi @erikbosch can you elaborate a bit on this? Do you already have sth in mind how a signal like this would be defined? 
I could take some time to implement this

**Comment by erikbosch** [comment]
Hi @nwesem - I will try to explain some ideas that I had at that time. The problem as of today is that you need quite many lines to change a signals, like using `delete` below.

```yaml
Vehicle.Service.TimeToService:
  type: sensor
  datatype: int32
  delete: true
```

(Parts of it is due to tool limitations, that we for instance require `type` even if we theoretically could manage without for overlays). Anyhow, if we would like to use `delete` for a large number of signals it would be great with a method where you only need a single line for each extra signal. One idea could be to support something like below where you define the wanted change (add/delete) and then just list all signals that shall be involved. Would likely be quite easy to implement **if** we support defining overlays without specifying type so that the tool just could expand it. But one could think of other ideas/solutions/syntax as well. The challenge is likely to find something that can be implemented without adding to much complexity 


```

delete_some:
  type: overlay
  add:
     delete: true
  signals:
    - dsdsd
    - dsssd
    - ds
    
define_safety:
  add:
     asil: qm
  signals:
    - a
    - d
    - f
    
remove_unit:
  remove:
     unit:
  signals:
    - xxx
    - yyy
    - zzz
```
