### ISSUE TITLE
Overlays on expanded tree?

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vss-tools#201]
There might for deployments be reasons to give additional data for individual signals, also for branches with instances. As of today we support overlays, but they are merged before we do instance expansion, so we cannot add information to individual instances. This could hypothetically be solved if we also add support for overlays to be merged after expansion. A hypothetical example below where we want to add a signal to the Row1.Pos1 seat, and in addition set min/max values for all seats. This is not possible with current tooling.

**Idea:**

_Shall we expand tooling so we can support two types of overlay insertion mechanisms, e.g. use `-o`for insertion before expansion, and `-o2` to insert after expansions?_ 

It would from a tooling perspective be a very easy solution.

Example:

```

#Something that only exist for one seat

Vehicle.Cabin.Seat.Row1.Pos1.IsHairDryerOn:
  type: actuator
  datatype: boolean

# Giving values that differ

Vehicle.Cabin.Seat.Row1.Pos1.Position:
  type: actuator
  datatype: uint16
  min: 0
  max: 125
  
Vehicle.Cabin.Seat.Row1.Pos2.Position:
  type: actuator
  datatype: uint16
  min: 0
  max: 125
  
Vehicle.Cabin.Seat.Row2.Pos1.Position:
  type: actuator
  datatype: uint16
  min: 0
  max: 60
  
Vehicle.Cabin.Seat.Row2.Pos2.Position:
  type: actuator
  datatype: uint16
  min: 0
  max: 60
```

**Comment by erikbosch** [comment]
Meeting notes:

- Ulf: Likes the idea, but `-o2` is not a good name
- Sebastian: two parts - one is if we need both before/after insertion of overlays, second questions is how
- Erik: Comment until next meeting

**Comment by argerus** [comment]
Hmm, maybe this is because I'm looking at it "from the outside"... but wouldn't it make a lot more sense to do it the other way around. That is:

Instead of forcing the user to manually specify whether the overlay should be applied before or after expansion, the tool can simply determine this on it's own based on the path provided in the overlay.

* If the overlay specifies `Vehicle.Cabin.Seat.Position`, it's quite obvious it should apply before expansion.

* If the overlay specifies `Vehicle.Cabin.Seat.Row1.Pos1.Position`, it's equally obvious it should be applied after expansion.

**Comment by erikbosch** [comment]
Theoretically the tool could do an educated guess and handle it based on that, but not "simply". It would require a bigger refactoring of the tooling. Today the merge and expansion is quite "stupid".  @SebastianSchildt has better knowledge on the internals and could possibly provide an estimate on time required to make it smarter.

**Comment by argerus** [comment]
> Theoretically the tool could do an educated guess and handle it based on that, but not "simply".

I don't see why it would be a guess. The tooling is doing the expansion, so it will know if a path is the result of an expansion or if it's not, right?

**Comment by erikbosch** [comment]
"Guess" is bad choice of word, I think "assumption" is a better word.  Taking an overlay example like below, the tool must make an assumption that if it find a name that matches a branch coming from instantiation, then the overlay shall be applied after expansion. 

```
# example 1: This shall only result in one new signal, the tool shall detect that "Row1.Pos1" refers to an instantiated path
# (Vehicle.Cabin.Seat.Row1.Pos1.NewSignal)
Vehicle.Cabin.Seat.Row1.Pos1.NewSignal:
  type: actuator
  datatype: uint16

#example 2: this shall result in 4 new signals, once for every row/pos combination.
# (Vehicle.Cabin.Seat.Row1.Pos1.A.B.NewSignal)
# (Vehicle.Cabin.Seat.Row1.Pos2.A.B.NewSignal)
# (Vehicle.Cabin.Seat.Row2.Pos1.A.B.NewSignal)
# (Vehicle.Cabin.Seat.Row2.Pos2.A.B.NewSignal)
Vehicle.Cabin.Seat.A.B.NewSignal:
  type: actuator
  datatype: uint16

# example 3: A bit of corner case as it include "Row1" but no "Pos*"
#    A possible semantics is that it then shall be expanded only for pos
# (Vehicle.Cabin.Seat.Row1.Pos1.Sebastian.NewSignal)
# (Vehicle.Cabin.Seat.Row1.Pos2.Sebastian.NewSignal)
Vehicle.Cabin.Seat.Row1.Sebastian.NewSignal:
  type: actuator
  datatype: uint16

```
