### ISSUE TITLE
Overlay annotations to indicate if a signal is supposed to already exist or not.

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vss-tools#227]
Today you can use overlays to both add new signals as well refactor existing signals. This gives a potential problem, if you do a spelling error or if a signal has been renamed or removed in standard VSS catalog your overlay may not do what you expect.

I am thinking if vss-tools possibly should support an attribute `overlay: ['add'|'refactor']` ( or similar like `new: True|False`) that could be used in overlays to describe if the overlay intend to add a new signal or change an existing signal. Then tooling could give a warning if the directive does not match reality.

```
Vehicle.Boddy.RefuelPosition:
  datatype: string
  type: attribute
  allowed: ['ALT1','ALT2']
  overlay: ['add'|'refactor']
  description: Location of the fuel cap or charge port.
```
