### ISSUE TITLE
Bug in DDSIDL when allowed string values could be a number

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vss-tools#276]
` vspec2ddsidl.py` does not escape/quote enum values - this gives problem if VSS uses string values but the value actually could be a numeric

**VSS**
```

PidsA:
  datatype: string[]
  type: attribute
  allowed: ["01","02","03","04","05","06","07","08","09","0A","0B","0C","0D","0E","0F","10","11","12","13","14","15","16","17","18","19","1A","1B","1C","1D","1E","1F","20"]
  description: PID 00 - Array of the supported PIDs 01 to 20 in Hexadecimal.
```

**Result:**
```
module PidsA_M
{
enum PidsAValues{01,02,03,04,05,06,07,08,09,0A,0B,0C,0D,0E,0F,10,11,12,13,14,15,16,17,18,19,1A,1B,1C,1D,1E,1F,20};
};
struct PidsA
{
PidsA_M::PidsAValues value;
//const string type ="attribute";
//const string description="PID 00 - Array of the supported PIDs 01 to 20 in Hexadecimal.";
};
```

This should better be fixed for VSS 4.0. Could be seen as a regression as the signal is new for VSS 4.0

FYI @AkhilTThomas and others - If anyone have time and interest providing a fix you are welcome. if not I will try to find a fix next week
