### ISSUE TITLE
DDSIDL: Cannot handle allowed values with blanks

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vss-tools#289]
vspec2ddsidl cannot handle string literals with included blanks, like below ( a blank after `WITH_`).

This is valid VSS (although not following VSS style guide), so vspec2ddsidl should preferably handle this, by ignoring/escaping so that the value becomes a legal DDSIDL value.

```
MySignal:
  datatype: string[]
  type: attribute
  allowed: ['NO_BLANK', 'WITH_ BLANK']
  description: string value with blank
```
