### ISSUE TITLE
Instance expansion buggy when using a mix of list unrolling and "normal"

### ISSUE THREAD

**Issue by sschleemilch** [COVESA/vss-tools#390]
Found while doing #382. Not sure if we should try to fix it though if we want to go with #382.

Test vspec:
```yaml
Vehicle:
  type: branch
  description: Vehicle

Vehicle.Door:
  description: Door
  type: branch
  instances:
  - Row[1,2]
  - RowId
  - Column[1,2]
  - ColumnId
```

Expected:
```yaml
Vehicle:
  description: Vehicle
  type: branch

Vehicle.Door:
  description: Door
  type: branch

Vehicle.Door.Row1:
  description: Door
  type: branch

Vehicle.Door.Row1.Column1:
  description: Door
  type: branch

Vehicle.Door.Row1.Column1.ColumnId:
  description: Door
  type: branch

Vehicle.Door.Row1.Column2:
  description: Door
  type: branch

Vehicle.Door.Row1.Column2.ColumnId:
  description: Door
  type: branch

Vehicle.Door.Row1.RowId:
  description: Door
  type: branch

Vehicle.Door.Row2:
  description: Door
  type: branch

Vehicle.Door.Row2.Column1:
  description: Door
  type: branch

Vehicle.Door.Row2.Column1.ColumnId:
  description: Door
  type: branch

Vehicle.Door.Row2.Column2:
  description: Door
  type: branch

Vehicle.Door.Row2.Column2.ColumnId:
  description: Door
  type: branch

Vehicle.Door.Row2.RowId:
  description: Door
  type: branch
```

Actual:
```yaml
Vehicle:
  description: Vehicle
  type: branch

Vehicle.Door:
  description: Door
  type: branch

Vehicle.Door.Row1:
  description: Door
  type: branch

Vehicle.Door.Row1.Column1:
  description: Door
  type: branch

Vehicle.Door.Row1.Column1.Column1:
  description: Door
  type: branch

Vehicle.Door.Row1.Column1.Column1.ColumnId:
  description: Door
  type: branch

Vehicle.Door.Row1.Column1.Column2:
  description: Door
  type: branch

Vehicle.Door.Row1.Column1.Column2.ColumnId:
  description: Door
  type: branch

Vehicle.Door.Row1.Column2:
  description: Door
  type: branch

Vehicle.Door.Row1.Column2.Column1:
  description: Door
  type: branch

Vehicle.Door.Row1.Column2.Column1.ColumnId:
  description: Door
  type: branch

Vehicle.Door.Row1.Column2.Column2:
  description: Door
  type: branch

Vehicle.Door.Row1.Column2.Column2.ColumnId:
  description: Door
  type: branch

Vehicle.Door.Row1.RowId:
  description: Door
  type: branch

Vehicle.Door.Row2:
  description: Door
  type: branch

Vehicle.Door.Row2.Column1:
  description: Door
  type: branch

Vehicle.Door.Row2.Column1.Column1:
  description: Door
  type: branch

Vehicle.Door.Row2.Column1.Column1.ColumnId:
  description: Door
  type: branch

Vehicle.Door.Row2.Column1.Column2:
  description: Door
  type: branch

Vehicle.Door.Row2.Column1.Column2.ColumnId:
  description: Door
  type: branch

Vehicle.Door.Row2.Column2:
  description: Door
  type: branch

Vehicle.Door.Row2.Column2.Column1:
  description: Door
  type: branch

Vehicle.Door.Row2.Column2.Column1.ColumnId:
  description: Door
  type: branch

Vehicle.Door.Row2.Column2.Column2:
  description: Door
  type: branch

Vehicle.Door.Row2.Column2.Column2.ColumnId:
  description: Door
  type: branch

Vehicle.Door.Row2.RowId:
  description: Door
  type: branch

```

**Comment by erikbosch** [comment]
I think the instance handling code as of today has some limitations. Looking at https://covesa.github.io/vehicle_signal_specification/rule_set/instances/ one can see that two "types" of instance declarations:


 * _a list of strings, where each element defines a single instance, e.g. ['DriverSide','PassengerSide'] results into two instances of every following data entry in the path, named DriverSide and PassengerSide_
* _a string, followed by a range defined through [n,m], with n,m as integer and n <= m, which defines the number of instances. Position[1,4] results into 4 instances of every following data entry in the path, named Position1, Position2, Position3 and Position4. It is in VSS recommended to use 1 as start index for the first row/axle/position/…_

If you use something else you can unfortunately get unexpected results. Like in your case when `- RowId` is neither a "prefix+range" or "list of strings". Do you get what you expect if you define it like below?

```
Vehicle.Door:
  description: Door
  type: branch
  instances:
  - Row[1,2]
  - [RowId]
  - Column[1,2]
  - [ColumnId]
```

As long as we only intend to support `<string>[<min>,<max>]` and `[<literal1>, <literal2>,...]` then an example like your should preferably give an error. I have by the way thought of having a more elaborate instance syntax, see https://github.com/COVESA/vehicle_signal_specification/issues/642
